In [1]:
import sys
# !{sys.executable} -m pip install -U pandas-profiling[notebook]
# !jupyter nbextension enable --py widgetsnbextension
# !pip install matplotlib
# !pip install graphviz

In [2]:
import os
import numpy as np
import pandas as pd

In [5]:
df= pd.read_csv(r'C:\Users\zdehg\Downloads\archive\DASS_data_21.02.19\data.csv',  error_bad_lines=False, warn_bad_lines=False, sep=r'\t' )

C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


In [23]:
from sklearn import tree
help(tree.DecisionTreeClassifier)

Help on class DecisionTreeClassifier in module sklearn.tree._classes:

class DecisionTreeClassifier(sklearn.base.ClassifierMixin, BaseDecisionTree)
 |  DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, ccp_alpha=0.0)
 |  
 |  A decision tree classifier.
 |  
 |  Read more in the :ref:`User Guide <tree>`.
 |  
 |  Parameters
 |  ----------
 |  criterion : {"gini", "entropy"}, default="gini"
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "entropy" for the information gain.
 |  
 |  splitter : {"best", "random"}, default="best"
 |      The strategy used to choose the split at each node. Supported
 |      strategies are "best" to choose the best split and "random" to choose
 |      the best ran

In [24]:
def clasVar(df):
    conditions = [
    (df['Depression'] >= 14) ,
    (df['Anxiety'] >= 10)  ,
    (df['Stress'] >= 19), 
    ((df['Depression'] < 14)  & (df['Anxiety'] < 10) & (df['Stress'] < 19)),
    ]
    values = ['Severly Depressed','Severely axious', 'Severly Stressed', 'Normal']
    df['diagnosis Category'] = np.select(conditions, values)
    return df

In [26]:
dfNew = clasVar(df)
dfNew.head(10)

Q1A  Q1I   Q1E  Q2A  Q2I   Q2E  Q3A  Q3I    Q3E  Q4A  ...  Anxiety  \
0    4   28  3890    4   25  2122    2   16   1944    4  ...       34   
1    4    2  8118    1   36  2890    2   35   4777    3  ...       17   
2    3    7  5784    1   33  4373    4   41   3242    1  ...       12   
3    2   23  5081    3   11  6837    2   37   5521    1  ...       17   
4    2   36  3215    2   13  7731    3    5   4156    4  ...       40   
5    1   18  6116    1   28  3193    2    2  12542    1  ...        6   
6    1   20  4325    1   34  4009    2   38   3604    3  ...       19   
7    1   34  4796    1    9  2618    1   39   5823    1  ...        4   
8    4    4  3470    4   14  2139    3    1  11043    4  ...       39   
9    3   38  5187    2   28  2600    4    9   2015    1  ...       28   

   Anxiety_cat  Stress  Stress_cat  Extraversion  Agreeableness  \
0            4      40           4           0.5            4.5   
1            3      27           3           4.5            4.5   
2            2      17           1           1.5            3.5   
3            3      16           1           2.0            6.0   
4            4      29           3           2.0            3.5   
5            0      12           0           1.0            6.5   
6            3      14           0           3.5            4.0   
7            0       6           0           6.0            3.5   
8            4      33           3           0.5            4.5   
9            4      34           4           0.5            0.5   

   Conscientiousness  EmotionalStability  Openness  diagnosis Category  
0                4.5                 0.5       6.5   Severly Depressed  
1                2.0                 0.5       3.5   Severly Depressed  
2                2.0                 4.0       5.0   Severly Depressed  
3                6.5                 4.5       6.0   Severly Depressed  
4                2.0                 2.0       4.5   Severly Depressed  
5                5.5                 6.0       3.5              Normal  
6                5.0                 3.5       2.5   Severly Depressed  
7                4.0                 3.5       4.0              Normal  
8                2.5                 0.5       4.0   Severly Depressed  
9                5.0                 0.5       2.5   Severly Depressed  

[10 rows x 184 columns]

In [27]:
dfNew = dfNew.loc[:,['Extraversion', 'Agreeableness', 'Conscientiousness', 'EmotionalStability', 'Openness', 'diagnosis Category']]
dfNew

Extraversion  Agreeableness  Conscientiousness  EmotionalStability  \
0               0.5            4.5                4.5                 0.5   
1               4.5            4.5                2.0                 0.5   
2               1.5            3.5                2.0                 4.0   
3               2.0            6.0                6.5                 4.5   
4               2.0            3.5                2.0                 2.0   
...             ...            ...                ...                 ...   
39770           2.0            5.0                3.5                 2.5   
39771           2.5            3.0                2.5                 2.0   
39772           5.0            3.5                6.5                 3.5   
39773           1.5            2.0                3.5                 1.5   
39774           5.0            5.0                2.5                 1.5   

       Openness diagnosis Category  
0           6.5  Severly Depressed  
1           3.5  Severly Depressed  
2           5.0  Severly Depressed  
3           6.0  Severly Depressed  
4           4.5  Severly Depressed  
...         ...                ...  
39770       3.5  Severly Depressed  
39771       3.5  Severly Depressed  
39772       4.5             Normal  
39773       3.0  Severly Depressed  
39774       5.5  Severly Depressed  

[39775 rows x 6 columns]

In [28]:
dfNew.describe()

Extraversion  Agreeableness  Conscientiousness  EmotionalStability  \
count  39775.000000   39775.000000       39775.000000        39775.000000   
mean       2.967278       4.040377           3.730660            2.738290   
std        1.555143       1.229776           1.491769            1.527743   
min        0.000000       0.000000           0.000000            0.000000   
25%        1.500000       3.500000           2.500000            1.500000   
50%        3.000000       4.000000           3.500000            2.500000   
75%        4.000000       5.000000           5.000000            3.500000   
max        7.000000       7.000000           7.000000            7.000000   

           Openness  
count  39775.000000  
mean       4.101634  
std        1.335035  
min        0.000000  
25%        3.500000  
50%        4.000000  
75%        5.000000  
max        7.000000

In [30]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
# Our class column is Creditability here and everything else will be used as features 
class_col_name='diagnosis Category' 

feature_names=dfNew.columns[dfNew.columns != class_col_name ]
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(dfNew.loc[:, feature_names], dfNew[class_col_name], test_size=0.25,random_state=1)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(29831, 5) (29831,) (9944, 5) (9944,)


In [31]:
#because the graphviz package was not available in my system I used this method to show the decision tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
clf = tree.DecisionTreeClassifier(random_state=0 , max_depth=5)
decision_tree = clf.fit(X_train, y_train)
r = export_text(decision_tree, ['Extraversion', 'Agreeableness', 'Conscientiousness', 'EmotionalStability', 'Openness'])
print(r)

|--- EmotionalStability <= 3.25
|   |--- EmotionalStability <= 2.25
|   |   |--- EmotionalStability <= 1.25
|   |   |   |--- Extraversion <= 4.75
|   |   |   |   |--- Conscientiousness <= 3.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |   |--- Conscientiousness >  3.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |--- Extraversion >  4.75
|   |   |   |   |--- Conscientiousness <= 3.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |   |--- Conscientiousness >  3.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |--- EmotionalStability >  1.25
|   |   |   |--- Conscientiousness <= 4.25
|   |   |   |   |--- Extraversion <= 4.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |   |--- Extraversion >  4.25
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |--- Conscientiousness >  4.25
|   |   |   |   |--- Extraversion <= 3.75
|   |   |   |   |   |--- class: Severly Depressed
|   |   |   |   |--- Extra

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass feature_names=['Extraversion', 'Agreeableness', 'Conscientiousness', 'EmotionalStability', 'Openness'] as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [32]:
y_pred = clf.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)


Confusion Matrix
[[ 818    0 1160    0]
 [ 171    0  921    0]
 [ 320    0 6431    0]
 [  14    0  109    0]]


In [34]:
from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

                   precision    recall  f1-score   support

           Normal       0.62      0.41      0.50      1978
  Severely axious       0.00      0.00      0.00      1092
Severly Depressed       0.75      0.95      0.84      6751
 Severly Stressed       0.00      0.00      0.00       123

         accuracy                           0.73      9944
        macro avg       0.34      0.34      0.33      9944
     weighted avg       0.63      0.73      0.67      9944



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
